# TCL File Generated by Component Editor 18.1
# Sun Sep 29 19:11:40 EDT 2024
# DO NOT MODIFY


# 
# pio_n_out "Parallel IO N-bit Output" v1.0
#  2024.09.29.19:11:40
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module pio_n_out
# 
set_module_property DESCRIPTION ""
set_module_property NAME pio_n_out
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Parallel IO N-bit Output"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL pio_n_out
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file pio_n_out.sv SYSTEM_VERILOG PATH pio_n_out.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter bus_width INTEGER 64 ""
set_parameter_property bus_width DEFAULT_VALUE 64
set_parameter_property bus_width DISPLAY_NAME bus_width
set_parameter_property bus_width WIDTH ""
set_parameter_property bus_width TYPE INTEGER
set_parameter_property bus_width UNITS None
set_parameter_property bus_width ALLOWED_RANGES -2147483648:2147483647
set_parameter_property bus_width DESCRIPTION ""
set_parameter_property bus_width HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input bus_width
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pio_n_out
# 
add_interface pio_n_out conduit end
set_interface_property pio_n_out associatedClock clock
set_interface_property pio_n_out associatedReset reset
set_interface_property pio_n_out ENABLED true
set_interface_property pio_n_out EXPORT_OF ""
set_interface_property pio_n_out PORT_NAME_MAP ""
set_interface_property pio_n_out CMSIS_SVD_VARIABLES ""
set_interface_property pio_n_out SVD_ADDRESS_GROUP ""

add_interface_port pio_n_out pio_out export Output bus_width

