	soc_system u0 (
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_clk         (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_clk>),         // alt_vip_cl_cvo_hdmi_clocked_video.vid_clk
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_data        (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_data>),        //                                  .vid_data
		.alt_vip_cl_cvo_hdmi_clocked_video_underflow       (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_underflow>),       //                                  .underflow
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_mode_change (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_mode_change>), //                                  .vid_mode_change
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_std         (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_std>),         //                                  .vid_std
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_datavalid   (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_datavalid>),   //                                  .vid_datavalid
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_v_sync      (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_v_sync>),      //                                  .vid_v_sync
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_h_sync      (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_h_sync>),      //                                  .vid_h_sync
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_f           (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_f>),           //                                  .vid_f
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_h           (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_h>),           //                                  .vid_h
		.alt_vip_cl_cvo_hdmi_clocked_video_vid_v           (<connected-to-alt_vip_cl_cvo_hdmi_clocked_video_vid_v>),           //                                  .vid_v
		.arduino_gpio_export                               (<connected-to-arduino_gpio_export>),                               //                      arduino_gpio.export
		.button_pio_export                                 (<connected-to-button_pio_export>),                                 //                        button_pio.export
		.clk_clk                                           (<connected-to-clk_clk>),                                           //                               clk.clk
		.clk_hdmi_clk                                      (<connected-to-clk_hdmi_clk>),                                      //                          clk_hdmi.clk
		.ctrl_reg_export                                   (<connected-to-ctrl_reg_export>),                                   //                          ctrl_reg.export
		.dipsw_pio_export                                  (<connected-to-dipsw_pio_export>),                                  //                         dipsw_pio.export
		.gpio_0_a_export                                   (<connected-to-gpio_0_a_export>),                                   //                          gpio_0_a.export
		.gpio_0_b_export                                   (<connected-to-gpio_0_b_export>),                                   //                          gpio_0_b.export
		.gpio_1_a_export                                   (<connected-to-gpio_1_a_export>),                                   //                          gpio_1_a.export
		.gpio_1_b_export                                   (<connected-to-gpio_1_b_export>),                                   //                          gpio_1_b.export
		.hps_0_f2h_cold_reset_req_reset_n                  (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),                  //          hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n                 (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),                 //         hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents              (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),              //           hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n                  (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),                  //          hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n                           (<connected-to-hps_0_h2f_reset_reset_n>),                           //                   hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),             //                      hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),               //                                  .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),               //                                  .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),               //                                  .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),               //                                  .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),               //                                  .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),               //                                  .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC                (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),                //                                  .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),             //                                  .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),             //                                  .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK             (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),             //                                  .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),               //                                  .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),               //                                  .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3               (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),               //                                  .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD                 (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),                 //                                  .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),                  //                                  .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),                  //                                  .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK                 (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),                 //                                  .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),                  //                                  .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3                  (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),                  //                                  .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),                  //                                  .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),                  //                                  .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),                  //                                  .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),                  //                                  .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),                  //                                  .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),                  //                                  .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),                  //                                  .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7                  (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),                  //                                  .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),                 //                                  .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),                 //                                  .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),                 //                                  .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT                 (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),                 //                                  .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK                (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),                //                                  .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI               (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),               //                                  .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO               (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),               //                                  .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0                (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),                //                                  .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX                 (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),                 //                                  .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX                 (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),                 //                                  .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA                 (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),                 //                                  .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL                 (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),                 //                                  .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA                 (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),                 //                                  .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL                 (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),                 //                                  .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),              //                                  .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),              //                                  .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),              //                                  .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),              //                                  .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),              //                                  .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61              (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),              //                                  .hps_io_gpio_inst_GPIO61
		.hps_0_i2c2_out_data                               (<connected-to-hps_0_i2c2_out_data>),                               //                        hps_0_i2c2.out_data
		.hps_0_i2c2_sda                                    (<connected-to-hps_0_i2c2_sda>),                                    //                                  .sda
		.hps_0_i2c2_clk_clk                                (<connected-to-hps_0_i2c2_clk_clk>),                                //                    hps_0_i2c2_clk.clk
		.hps_0_i2c2_scl_in_clk                             (<connected-to-hps_0_i2c2_scl_in_clk>),                             //                 hps_0_i2c2_scl_in.clk
		.hps_0_i2c3_out_data                               (<connected-to-hps_0_i2c3_out_data>),                               //                        hps_0_i2c3.out_data
		.hps_0_i2c3_sda                                    (<connected-to-hps_0_i2c3_sda>),                                    //                                  .sda
		.hps_0_i2c3_clk_clk                                (<connected-to-hps_0_i2c3_clk_clk>),                                //                    hps_0_i2c3_clk.clk
		.hps_0_i2c3_scl_in_clk                             (<connected-to-hps_0_i2c3_scl_in_clk>),                             //                 hps_0_i2c3_scl_in.clk
		.hps_0_spim0_txd                                   (<connected-to-hps_0_spim0_txd>),                                   //                       hps_0_spim0.txd
		.hps_0_spim0_rxd                                   (<connected-to-hps_0_spim0_rxd>),                                   //                                  .rxd
		.hps_0_spim0_ss_in_n                               (<connected-to-hps_0_spim0_ss_in_n>),                               //                                  .ss_in_n
		.hps_0_spim0_ssi_oe_n                              (<connected-to-hps_0_spim0_ssi_oe_n>),                              //                                  .ssi_oe_n
		.hps_0_spim0_ss_0_n                                (<connected-to-hps_0_spim0_ss_0_n>),                                //                                  .ss_0_n
		.hps_0_spim0_ss_1_n                                (<connected-to-hps_0_spim0_ss_1_n>),                                //                                  .ss_1_n
		.hps_0_spim0_ss_2_n                                (<connected-to-hps_0_spim0_ss_2_n>),                                //                                  .ss_2_n
		.hps_0_spim0_ss_3_n                                (<connected-to-hps_0_spim0_ss_3_n>),                                //                                  .ss_3_n
		.hps_0_spim0_sclk_out_clk                          (<connected-to-hps_0_spim0_sclk_out_clk>),                          //              hps_0_spim0_sclk_out.clk
		.hps_0_uart1_cts                                   (<connected-to-hps_0_uart1_cts>),                                   //                       hps_0_uart1.cts
		.hps_0_uart1_dsr                                   (<connected-to-hps_0_uart1_dsr>),                                   //                                  .dsr
		.hps_0_uart1_dcd                                   (<connected-to-hps_0_uart1_dcd>),                                   //                                  .dcd
		.hps_0_uart1_ri                                    (<connected-to-hps_0_uart1_ri>),                                    //                                  .ri
		.hps_0_uart1_dtr                                   (<connected-to-hps_0_uart1_dtr>),                                   //                                  .dtr
		.hps_0_uart1_rts                                   (<connected-to-hps_0_uart1_rts>),                                   //                                  .rts
		.hps_0_uart1_out1_n                                (<connected-to-hps_0_uart1_out1_n>),                                //                                  .out1_n
		.hps_0_uart1_out2_n                                (<connected-to-hps_0_uart1_out2_n>),                                //                                  .out2_n
		.hps_0_uart1_rxd                                   (<connected-to-hps_0_uart1_rxd>),                                   //                                  .rxd
		.hps_0_uart1_txd                                   (<connected-to-hps_0_uart1_txd>),                                   //                                  .txd
		.led_pio_export                                    (<connected-to-led_pio_export>),                                    //                           led_pio.export
		.memory_mem_a                                      (<connected-to-memory_mem_a>),                                      //                            memory.mem_a
		.memory_mem_ba                                     (<connected-to-memory_mem_ba>),                                     //                                  .mem_ba
		.memory_mem_ck                                     (<connected-to-memory_mem_ck>),                                     //                                  .mem_ck
		.memory_mem_ck_n                                   (<connected-to-memory_mem_ck_n>),                                   //                                  .mem_ck_n
		.memory_mem_cke                                    (<connected-to-memory_mem_cke>),                                    //                                  .mem_cke
		.memory_mem_cs_n                                   (<connected-to-memory_mem_cs_n>),                                   //                                  .mem_cs_n
		.memory_mem_ras_n                                  (<connected-to-memory_mem_ras_n>),                                  //                                  .mem_ras_n
		.memory_mem_cas_n                                  (<connected-to-memory_mem_cas_n>),                                  //                                  .mem_cas_n
		.memory_mem_we_n                                   (<connected-to-memory_mem_we_n>),                                   //                                  .mem_we_n
		.memory_mem_reset_n                                (<connected-to-memory_mem_reset_n>),                                //                                  .mem_reset_n
		.memory_mem_dq                                     (<connected-to-memory_mem_dq>),                                     //                                  .mem_dq
		.memory_mem_dqs                                    (<connected-to-memory_mem_dqs>),                                    //                                  .mem_dqs
		.memory_mem_dqs_n                                  (<connected-to-memory_mem_dqs_n>),                                  //                                  .mem_dqs_n
		.memory_mem_odt                                    (<connected-to-memory_mem_odt>),                                    //                                  .mem_odt
		.memory_mem_dm                                     (<connected-to-memory_mem_dm>),                                     //                                  .mem_dm
		.memory_oct_rzqin                                  (<connected-to-memory_oct_rzqin>),                                  //                                  .oct_rzqin
		.random_reg_export                                 (<connected-to-random_reg_export>),                                 //                        random_reg.export
		.reset_val_export                                  (<connected-to-reset_val_export>)                                   //                         reset_val.export
	);

